name: whiteboard_server
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  args: ^2.0.0
  shelf: ^1.1.4
  shelf_web_socket: ^1.0.1
  web_socket_channel: ^2.1.0
  path: ^1.7.0
  web_whiteboard:
    path: ../
    # git: https://github.com/doodlezucc/web_drawing.git

dev_dependencies:
  build_runner: ^2.1.7
  build_web_compilers: ^3.2.2
  lint: ^1.8.2
