name: whiteboard_server
description: A simple command-line application.

environment:
  sdk: ">=2.15.0 <4.0.0"

dependencies:
  args: ^2.0.0
  shelf: ^1.1.4
  shelf_web_socket: ^1.0.1
  web_socket_channel: ^2.1.0
  path: ^1.7.0
  web_whiteboard:
    path: ../

dev_dependencies:
  build_runner: ^2.1.7
  build_web_compilers: ^4.0.4
  lint: ^2.1.2
